{% set name = "mubody" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mubody-{{ version }}.tar.gz
  sha256: bbd519b96e8d7b82e29be540eee845576ca7d58fec12069a5f0c0b31bb564a53

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools >=61
    - pip
  run:
    - python >=3.8
    - numpy
    - scipy
    - pandas
    - matplotlib-base
    - tqdm
    - astropy-base
    - spiceypy
    - numba
    - requests

test:
  imports:
    - mubody

about:
  home: https://gitlab.com/mubody/mubody
  summary: Multi-body dynamics in libration points
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - JuanBermejo
